version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PORT=8000

  dashboard:
    build:
      context: .
      dockerfile: dashboard.Dockerfile
    ports:
      - "8050:8050"
    environment:
      - API_URL=http://api:8000
      - PORT=8050
    depends_on:
      - api
